- job:
    name: networking-bgpvpn-bagpipe-dsvm-functional
    parent: legacy-dsvm-base
    run: playbooks/networking-bgpvpn-bagpipe-dsvm-functional/run.yaml
    post-run: playbooks/networking-bgpvpn-bagpipe-dsvm-functional/post.yaml
    timeout: 7800
    required-projects:
      - openstack/devstack-gate
      - openstack/networking-bagpipe
      - openstack/networking-bgpvpn

- job:
    name: networking-bgpvpn-bagpipe-dsvm-install
    parent: legacy-dsvm-base
    run: playbooks/networking-bgpvpn-bagpipe-dsvm-install/run.yaml
    post-run: playbooks/networking-bgpvpn-bagpipe-dsvm-install/post.yaml
    timeout: 7800
    required-projects:
      - openstack/devstack-gate
      - openstack/networking-bagpipe
      - openstack/networking-bgpvpn

- job:
    name: networking-bgpvpn-dsvm-functional
    parent: legacy-dsvm-base
    pre-run: playbooks/networking-bgpvpn-dsvm-functional/pre.yaml
    run: playbooks/networking-bgpvpn-dsvm-functional/run.yaml
    post-run: playbooks/networking-bgpvpn-dsvm-functional/post.yaml
    timeout: 7800
    required-projects:
      - openstack/devstack-gate
      - openstack/networking-bgpvpn
      - openstack/neutron
      - openstack/networking-bagpipe
      - openstack/networking-odl
      - openstack/horizon

- job:
    name: networking-bgpvpn-dsvm-install
    parent: legacy-dsvm-base
    run: playbooks/networking-bgpvpn-dsvm-install/run.yaml
    post-run: playbooks/networking-bgpvpn-dsvm-install/post.yaml
    timeout: 7800
    required-projects:
      - openstack/devstack-gate
      - openstack/networking-bgpvpn

- project:
    templates:
      - openstack-python-jobs-neutron
      - openstack-python35-jobs-neutron
      - openstack-python36-jobs-neutron
      - openstack-python37-jobs-neutron
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
      - periodic-stable-jobs-neutron
      - check-requirements
    check:
      jobs:
        - openstack-tox-lower-constraints:
            voting: false
            required-projects:
              - openstack/neutron
              - openstack/networking-bagpipe
              - openstack/horizon
        - horizon-openstack-tox-python3-django111
        - openstack-tox-pep8:
            required-projects:
              - openstack/networking-bagpipe
              - openstack/horizon
        - openstack-tox-py27:
            required-projects:
              - openstack/networking-bagpipe
              - openstack/horizon
        - openstack-tox-py35:
            required-projects:
              - openstack/networking-bagpipe
              - openstack/horizon
        - openstack-tox-py36:
            required-projects:
              - openstack/networking-bagpipe
              - openstack/horizon
        - openstack-tox-py37:
            required-projects:
              - openstack/networking-bagpipe
              - openstack/horizon
        - legacy-tempest-dsvm-networking-bgpvpn-bagpipe:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - openstack-tox-cover:
            required-projects:
              - openstack/neutron
              - openstack/networking-bagpipe
              - openstack/horizon
        - networking-bgpvpn-dsvm-functional
        - requirements-check:
            nodeset: ubuntu-bionic
    gate:
      jobs:
        - openstack-tox-lower-constraints:
            voting: false
            required-projects:
              - openstack/neutron
              - openstack/networking-bagpipe
              - openstack/horizon
        - horizon-openstack-tox-python3-django111
        - openstack-tox-pep8:
            required-projects:
              - openstack/networking-bagpipe
              - openstack/horizon
        - openstack-tox-py27:
            required-projects:
              - openstack/networking-bagpipe
              - openstack/horizon
        - openstack-tox-py35:
            required-projects:
              - openstack/networking-bagpipe
              - openstack/horizon
        - openstack-tox-py36:
            required-projects:
              - openstack/networking-bagpipe
              - openstack/horizon
        - openstack-tox-py37:
            required-projects:
              - openstack/networking-bagpipe
              - openstack/horizon
        - legacy-tempest-dsvm-networking-bgpvpn-bagpipe:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - networking-bgpvpn-dsvm-functional
        - requirements-check:
            nodeset: ubuntu-bionic
    experimental:
      jobs:
        - networking-bgpvpn-dsvm-install
        - networking-bgpvpn-bagpipe-dsvm-install
        - networking-bgpvpn-bagpipe-dsvm-functional
